# Generated by Django 5.0.6 on 2024-05-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='author',
        ),
    ]
