# Generated by Django 5.0.6 on 2024-05-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_resume_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
    ]
