# Generated by Django 5.0.6 on 2024-05-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_resume_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
    ]
