# Generated by Django 5.0.6 on 2024-05-22 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vacancy_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='fullName',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='fullName'),
            preserve_default=False,
        ),
    ]
