# Generated by Django 5.0.6 on 2024-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resume_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='fullName',
            field=models.TextField(max_length=70, verbose_name='fullName'),
        ),
    ]
